archlinux:
  image: "archlinux:latest"
  before_script:
    - pacman -Sy base-devel cmake wget --noconfirm --needed
  script:
    - mkdir build && cd build && cmake ../ && make && cd ../
    - ./tests/stockfish.sh && ./tests/berserk.sh
    - cd build && ctest
